# Import flat files from the web

The utils functions to import flat file data, such as read.csv() and read.delim(), are capable of automatically importing from URLs that point to flat files on the web. Also from the readr library read_csv() and also read_tsv().

In [1]:
# Load the readr package
library(readr)

# Import the csv file: pools
url_csv <- "http://s3.amazonaws.com/assets.datacamp.com/production/course_1478/datasets/swimming_pools.csv"


# Import the txt file: potatoes
url_delim <- "http://s3.amazonaws.com/assets.datacamp.com/production/course_1478/datasets/potatoes.txt"


# Print pools and potatoes
pools <- read_csv(url_csv)
potatoes <- read_tsv(url_delim)

head(pools)
head(potatoes)

Parsed with column specification:
cols(
  Name = col_character(),
  Address = col_character(),
  Latitude = col_double(),
  Longitude = col_double()
)
Parsed with column specification:
cols(
  area = col_integer(),
  temp = col_integer(),
  size = col_integer(),
  storage = col_integer(),
  method = col_integer(),
  texture = col_double(),
  flavor = col_double(),
  moistness = col_double()
)

  Name                        Address
1 Acacia Ridge Leisure Centre 1391 Beaudesert Road, Acacia Ridge
2 Bellbowrie Pool             Sugarwood Street, Bellbowrie
3 Carole Park                 Cnr Boundary Road and Waterford Road Wacol
4 Centenary Pool (inner City) 400 Gregory Terrace, Spring Hill
5 Chermside Pool              375 Hamilton Road, Chermside
6 Colmslie Pool (Morningside) 400 Lytton Road, Morningside
  Latitude  Longitude
1 -27.58616 153.0264
2 -27.56547 152.8911
3 -27.60744 152.9315
4 -27.45537 153.0251
5 -27.38583 153.0351
6 -27.45516 153.0789

  area temp size storage method texture flavor moistness
1 1    1    1    1       1      2.9     3.2    3.0
2 1    1    1    1       2      2.3     2.5    2.6
3 1    1    1    1       3      2.5     2.8    2.8
4 1    1    1    1       4      2.1     2.9    2.4
5 1    1    1    1       5      1.9     2.8    2.2
6 1    1    1    2       1      1.8     3.0    1.7

## Secure importing

In the previous exercises, you have been working with URLs that all start with http://. There is, however, a safer alternative to HTTP, namely HTTPS, which stands for HypterText Transfer Protocol Secure. Just remember this: HTTPS is relatively safe, HTTP is not.

In [2]:
# https URL to the swimming_pools csv file.
url_csv <- "https://s3.amazonaws.com/assets.datacamp.com/production/course_1478/datasets/swimming_pools.csv"

# Import the file using read.csv(): pools1
pools1 <- read.csv(url_csv)

# Load the readr package
library(readr)

# Import the file using read_csv(): pools2
pools2 <- read_csv(url_csv)

# Print the structure of pools1 and pools2
str(pools1)
str(pools2)

Parsed with column specification:
cols(
  Name = col_character(),
  Address = col_character(),
  Latitude = col_double(),
  Longitude = col_double()
)

'data.frame':	20 obs. of  4 variables:
 $ Name     : Factor w/ 20 levels "Acacia Ridge Leisure Centre",..: 1 2 3 4 5 6 19 7 8 9 ...
 $ Address  : Factor w/ 20 levels "1 Fairlead Crescent, Manly",..: 5 20 18 10 9 11 6 15 12 17 ...
 $ Latitude : num  -27.6 -27.6 -27.6 -27.5 -27.4 ...
 $ Longitude: num  153 153 153 153 153 ...
Classes 'tbl_df', 'tbl' and 'data.frame':	20 obs. of  4 variables:
 $ Name     : chr  "Acacia Ridge Leisure Centre" "Bellbowrie Pool" "Carole Park" "Centenary Pool (inner City)" ...
 $ Address  : chr  "1391 Beaudesert Road, Acacia Ridge" "Sugarwood Street, Bellbowrie" "Cnr Boundary Road and Waterford Road Wacol" "400 Gregory Terrace, Spring Hill" ...
 $ Latitude : num  -27.6 -27.6 -27.6 -27.5 -27.4 ...
 $ Longitude: num  153 153 153 153 153 ...
 - attr(*, "spec")=List of 2
  ..$ cols   :List of 4
  .. ..$ Name     : list()
  .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
  .. ..$ Address  : list()
  .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
  .. ..$ Latitude : list()
  .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
  .. ..$ Longitude: list()
  .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
  ..$ default: list()
  .. ..- attr(*, "class")= chr  "collector_guess" "collector"
  ..- attr(*, "class")= chr "col_spec"

## Import Excel files from the web

When you learned about gdata, it was already mentioned that gdata can handle .xls files that are on the internet. readxl can't, at least not yet.

## Importing RData
with download.file() you can download any kind of file from the web, using HTTP and HTTPS: images, executable files, but also .RData files. An RData file is very efficient format to store R data.

You can load data from an RData file using the load() function, but this function does not accept a URL string as an argument. In this exercise, you'll first download the RData file securely, and then import the local data file.

In [4]:
# https URL to the wine RData file.
url_rdata <- "https://s3.amazonaws.com/assets.datacamp.com/production/course_1478/datasets/wine.RData"

# Download the wine file to your working directory
download.file(url_rdata, destfile = "wine_local.RData")

# Load the wine data into your workspace using load()
load("wine_local.RData")

# Print out the summary of the wine data
summary(wine)

    Alcohol        Malic acid        Ash        Alcalinity of ash
 Min.   :11.03   Min.   :0.74   Min.   :1.360   Min.   :10.60
 1st Qu.:12.36   1st Qu.:1.60   1st Qu.:2.210   1st Qu.:17.20
 Median :13.05   Median :1.87   Median :2.360   Median :19.50
 Mean   :12.99   Mean   :2.34   Mean   :2.366   Mean   :19.52
 3rd Qu.:13.67   3rd Qu.:3.10   3rd Qu.:2.560   3rd Qu.:21.50
 Max.   :14.83   Max.   :5.80   Max.   :3.230   Max.   :30.00
   Magnesium      Total phenols     Flavanoids    Nonflavanoid phenols
 Min.   : 70.00   Min.   :0.980   Min.   :0.340   Min.   :0.1300
 1st Qu.: 88.00   1st Qu.:1.740   1st Qu.:1.200   1st Qu.:0.2700
 Median : 98.00   Median :2.350   Median :2.130   Median :0.3400
 Mean   : 99.59   Mean   :2.292   Mean   :2.023   Mean   :0.3623
 3rd Qu.:107.00   3rd Qu.:2.800   3rd Qu.:2.860   3rd Qu.:0.4400
 Max.   :162.00   Max.   :3.880   Max.   :5.080   Max.   :0.6600
 Proanthocyanins Color intensity       Hue           Proline
 Min.   :0.410   Min.   : 1.280   Min.   :1.270   Min.   : 278.0
 1st Qu.:1.250   1st Qu.: 3.210   1st Qu.:1.930   1st Qu.: 500.0
 Median :1.550   Median : 4.680   Median :2.780   Median : 672.0
 Mean   :1.587   Mean   : 5.055   Mean   :2.604   Mean   : 745.1
 3rd Qu.:1.950   3rd Qu.: 6.200   3rd Qu.:3.170   3rd Qu.: 985.0
 Max.   :3.580   Max.   :13.000   Max.   :4.000   Max.   :1680.0

## HTTP? httr! (1)

Downloading a file from the Internet means sending a GET request and receiving the file you asked for. Internally, all the previously discussed functions use a GET request to download files.

httr provides a convenient function, GET() to execute this GET request. The result is a response object, that provides easy access to the status code, content-type and, of course, the actual content.

You can extract the content from the request using the content() function. At the time of writing, there are three ways to retrieve this content: as a raw object, as a character vector, or an R object, such as a list. If you don't tell content() how to retrieve the content through the as argument, it'll try its best to figure out which type is most appropriate based on the content-type.

In [5]:
# Load the httr package
library(httr)

# Get the url, save response to resp
url <- "http://www.example.com/"
resp <- GET(url)

# Print resp
resp

# Get the raw content of resp: raw_content
raw_content <- content(resp, as = "raw")

# Print the head of raw_content
head(raw_content)

Response [http://www.example.com/]
  Date: 2018-10-22 23:30
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 1.27 kB
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
...

[1] 3c 21 64 6f 63 74

# JSON
There are many other data formats out there. A very common one is JSON. This format is very often used by so-called Web APIs (Application Programming Interface), interfaces to web servers with which you as a client can communicate to get or store information in more complicated ways.

In [7]:
# Get the url
url <- "http://www.omdbapi.com/?apikey=ff21610b&t=Annie+Hall&y=&plot=short&r=json"
resp <- GET(url)

# Print resp
resp

# Print content of resp as text
text <- content(resp, as = "text")
text

# Print content of resp
content(resp)

Response [http://www.omdbapi.com/?apikey=ff21610b&t=Annie+Hall&y=&plot=short&r=json]
  Date: 2018-10-22 23:37
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 929 B

[1] "{\"Title\":\"Annie Hall\",\"Year\":\"1977\",\"Rated\":\"PG\",\"Released\":\"20 Apr 1977\",\"Runtime\":\"93 min\",\"Genre\":\"Comedy, Romance\",\"Director\":\"Woody Allen\",\"Writer\":\"Woody Allen, Marshall Brickman\",\"Actors\":\"Woody Allen, Diane Keaton, Tony Roberts, Carol Kane\",\"Plot\":\"Neurotic New York comedian Alvy Singer falls in love with the ditzy Annie Hall.\",\"Language\":\"English, German\",\"Country\":\"USA\",\"Awards\":\"Won 4 Oscars. Another 26 wins & 8 nominations.\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BZDg1OGQ4YzgtM2Y2NS00NjA3LWFjYTctMDRlMDI3NWE1OTUyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"8.0/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"97%\"},{\"Source\":\"Metacritic\",\"Value\":\"92/100\"}],\"Metascore\":\"92\",\"imdbRating\":\"8.0\",\"imdbVotes\":\"230,707\",\"imdbID\":\"tt0075686\",\"Type\":\"movie\",\"DVD\":\"28 Apr 1998\",\"BoxOffice\":\"N/A\",\"Production\":\"United Artists\",\"Website\":\"N/A\",\"Response\":\"True\"}"

$Title
[1] "Annie Hall"

$Year
[1] "1977"

$Rated
[1] "PG"

$Released
[1] "20 Apr 1977"

$Runtime
[1] "93 min"

$Genre
[1] "Comedy, Romance"

$Director
[1] "Woody Allen"

$Writer
[1] "Woody Allen, Marshall Brickman"

$Actors
[1] "Woody Allen, Diane Keaton, Tony Roberts, Carol Kane"

$Plot
[1] "Neurotic New York comedian Alvy Singer falls in love with the ditzy Annie Hall."

$Language
[1] "English, German"

$Country
[1] "USA"

$Awards
[1] "Won 4 Oscars. Another 26 wins & 8 nominations."

$Poster
[1] "https://m.media-amazon.com/images/M/MV5BZDg1OGQ4YzgtM2Y2NS00NjA3LWFjYTctMDRlMDI3NWE1OTUyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"

$Ratings
$Ratings[[1]]
$Ratings[[1]]$Source
[1] "Internet Movie Database"

$Ratings[[1]]$Value
[1] "8.0/10"


$Ratings[[2]]
$Ratings[[2]]$Source
[1] "Rotten Tomatoes"

$Ratings[[2]]$Value
[1] "97%"


$Ratings[[3]]
$Ratings[[3]]$Source
[1] "Metacritic"

$Ratings[[3]]$Value
[1] "92/100"



$Metascore
[1] "92"

$imdbRating
[1] "8.0"

$imdbVotes
[1] "230,707"

$imdbID
[1] "tt0075686"

$Type
[1] "movie"

$DVD
[1] "28 Apr 1998"

$BoxOffice
[1] "N/A"

$Production
[1] "United Artists"

$Website
[1] "N/A"

$Response
[1] "True"

A better way to load json files to R is with the package **jslonlite**

In [11]:
# Load the jsonlite package
library(jsonlite)

# wine_json is a JSON
wine_json <- '{"name":"Chateau Migraine", "year":1997, "alcohol_pct":12.4, "color":"red", "awarded":false}'
str(wine_json)
# Convert wine_json into a list: wine
wine <- fromJSON(wine_json)

# Print structure of wine
str(wine)

 chr "{\"name\":\"Chateau Migraine\", \"year\":1997, \"alcohol_pct\":12.4, \"color\":\"red\", \"awarded\":false}"
List of 5
 $ name       : chr "Chateau Migraine"
 $ year       : int 1997
 $ alcohol_pct: num 12.4
 $ color      : chr "red"
 $ awarded    : logi FALSE

In [12]:
# Definition of quandl_url
quandl_url <- "https://www.quandl.com/api/v3/datasets/WIKI/FB/data.json?auth_token=i83asDsiWUUyfoypkgMz"

# Import Quandl data: quandl_data
quandl_data <- fromJSON(quandl_url)

# Print structure of quandl_data
str(quandl_data)

List of 1
 $ dataset_data:List of 10
  ..$ limit       : NULL
  ..$ transform   : NULL
  ..$ column_index: NULL
  ..$ column_names: chr [1:13] "Date" "Open" "High" "Low" ...
  ..$ start_date  : chr "2012-05-18"
  ..$ end_date    : chr "2018-03-27"
  ..$ frequency   : chr "daily"
  ..$ data        : chr [1:1472, 1:13] "2018-03-27" "2018-03-26" "2018-03-23" "2018-03-22" ...
  ..$ collapse    : NULL
  ..$ order       : NULL

In [13]:
# Definition of the URLs
url_sw4 <- "http://www.omdbapi.com/?apikey=ff21610b&i=tt0076759&r=json"
url_sw3 <- "http://www.omdbapi.com/?apikey=ff21610b&i=tt0121766&r=json"

# Import two URLs with fromJSON(): sw4 and sw3
sw4 <- fromJSON(url_sw4)
sw3 <- fromJSON(url_sw3)

# Print out the Title element of both lists
sw4$Title
sw3$Title


# Is the release year of sw4 later than sw3?
sw4$Year > sw3$Year

[1] "Star Wars: Episode IV - A New Hope"

[1] "Star Wars: Episode III - Revenge of the Sith"

[1] FALSE

In [15]:
# fromJSON converst automatically to a dataframe, list, matric or vector
# Matrix
json1 <- '[[1, 2], [3, 4]]'
fromJSON(json1)

# data frame
json2 <- '[{"a": 1, "b": 2}, {"a": 3, "b": 4}, {"a" : 5, "b": 6}]'
fromJSON(json2)

# vector
json1 <- '[1, 2, 3, 4, 5, 6]'
fromJSON(json1)

# List
json2 <- '{"a": [1, 2, 3], "b" : [4, 5, 6]}'
fromJSON(json2)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

  a b
1 1 2
2 3 4
3 5 6

[1] 1 2 3 4 5 6

$a
[1] 1 2 3

$b
[1] 4 5 6

## toJSON()
You can also convert data to  a Json file. There are two versions of JSON files a pretty and mini version. The pretty is with whitespace, indentations etx and easy to read the mini version has no spaces at all.

In [16]:
# URL pointing to the .csv file
url_csv <- "http://s3.amazonaws.com/assets.datacamp.com/production/course_1478/datasets/water.csv"

# Import the .csv file located at url_csv
water <- read.csv(url_csv, stringsAsFactors = FALSE)

# Convert the data file according to the requirements
water_json <- toJSON(water)

# Print out water_json
water_json

[{"water":"Algeria","X1992":0.064,"X2002":0.017},{"water":"American Samoa"},{"water":"Angola","X1992":0.0001,"X2002":0.0001},{"water":"Antigua and Barbuda","X1992":0.0033},{"water":"Argentina","X1992":0.0007,"X1997":0.0007,"X2002":0.0007},{"water":"Australia","X1992":0.0298,"X2002":0.0298},{"water":"Austria","X1992":0.0022,"X2002":0.0022},{"water":"Bahamas","X1992":0.0013,"X2002":0.0074},{"water":"Bahrain","X1992":0.0441,"X2002":0.0441,"X2007":0.1024},{"water":"Barbados","X2007":0.0146},{"water":"British Virgin Islands","X2007":0.0042},{"water":"Canada","X1992":0.0027,"X2002":0.0027},{"water":"Cape Verde","X1992":0.002,"X1997":0.0017},{"water":"Cayman Islands","X1992":0.0033},{"water":"Central African Rep."},{"water":"Chile","X1992":0.0048,"X2002":0.0048},{"water":"Colombia","X1992":0.0027,"X2002":0.0027},{"water":"Cuba","X1992":0.0069,"X1997":0.0069,"X2002":0.0069},{"water":"Cyprus","X1992":0.003,"X1997":0.003,"X2002":0.0335},{"water":"Czech Rep.","X1992":0.0002,"X2002":0.0002},{"water":"Denmark","X1992":0.015,"X2002":0.015},{"water":"Djibouti","X1992":0.0001,"X2002":0.0001},{"water":"Ecuador","X1992":0.0022,"X1997":0.0022,"X2002":0.0022},{"water":"Egypt","X1992":0.025,"X1997":0.025,"X2002":0.1},{"water":"El Salvador","X1992":0.0001,"X2002":0.0001},{"water":"Finland","X1992":0.0001,"X2002":0.0001},{"water":"France","X1992":0.0117,"X2002":0.0117},{"water":"Gibraltar","X1992":0.0077},{"water":"Greece","X1992":0.01,"X2002":0.01},{"water":"Honduras","X1992":0.0002,"X2002":0.0002},{"water":"Hungary","X1992":0.0002,"X2002":0.0002},{"water":"India","X1997":0.0005,"X2002":0.0005},{"water":"Indonesia","X1992":0.0187,"X2002":0.0187},{"water":"Iran","X1992":0.003,"X1997":0.003,"X2002":0.003,"X2007":0.2},{"water":"Iraq","X1997":0.0074,"X2002":0.0074},{"water":"Ireland","X1992":0.0002,"X2002":0.0002},{"water":"Israel","X1992":0.0256,"X2002":0.0256,"X2007":0.14},{"water":"Italy","X1992":0.0973,"X2002":0.0973},{"water":"Jamaica","X1992":0.0005,"X1997":0.0005,"X2002":0.0005},{"water":"Japan","X1997":0.04,"X2002":0.04},{"water":"Jordan","X1997":0.002,"X2007":0.0098},{"water":"Kazakhstan","X1997":1.328,"X2002":1.328},{"water":"Kuwait","X1992":0.507,"X1997":0.231,"X2002":0.4202},{"water":"Lebanon","X2007":0.0473},{"water":"Libya","X2002":0.018},{"water":"Malaysia","X1992":0.0043,"X2002":0.0043},{"water":"Maldives","X1992":0.0004},{"water":"Malta","X1992":0.024,"X1997":0.031,"X2002":0.031},{"water":"Marshall Islands","X1992":0.0007},{"water":"Mauritania","X1992":0.002,"X2002":0.002},{"water":"Mexico","X1992":0.0307,"X2002":0.0307},{"water":"Morocco","X1992":0.0034,"X1997":0.0034,"X2002":0.007},{"water":"Namibia","X1992":0.0003,"X2002":0.0003},{"water":"Netherlands Antilles","X1992":0.063},{"water":"Nicaragua","X1992":0.0002,"X2002":0.0002},{"water":"Nigeria","X1992":0.003,"X2002":0.003},{"water":"Norway","X1992":0.0001,"X2002":0.0001},{"water":"Oman","X1997":0.034,"X2002":0.034,"X2007":0.109},{"water":"Peru","X1992":0.0054,"X2002":0.0054},{"water":"Poland","X1992":0.007,"X2002":0.007},{"water":"Portugal","X1992":0.0016,"X2002":0.0016},{"water":"Qatar","X1992":0.065,"X1997":0.099,"X2002":0.099,"X2007":0.18},{"water":"Saudi Arabia","X1992":0.683,"X1997":0.727,"X2002":0.863,"X2007":1.033},{"water":"Senegal","X1992":0,"X2002":0},{"water":"Somalia","X1992":0.0001,"X2002":0.0001},{"water":"South Africa","X1992":0.018,"X2002":0.018},{"water":"Spain","X1992":0.1002,"X2002":0.1002},{"water":"Sudan","X1992":0.0004,"X1997":0.0004,"X2002":0.0004},{"water":"Sweden","X1992":0.0002,"X2002":0.0002},{"water":"Trinidad and Tobago","X2007":0.036},{"water":"Tunisia","X1992":0.008,"X2002":0.013},{"water":"Turkey","X1992":0.0005,"X2002":0.0005,"X2007":0.0005},{"water":"United Arab Emirates","X1992":0.163,"X1997":0.385,"X2007":0.95},{"water":"United Kingdom","X1992":0.0333,"X2002":0.0333},{"water":"United States","X1992":0.58,"X2002":0.58},{"water":"Venezuela","X1992":0.0052,"X2002":0.0052},{"water":"Yemen, Rep.","X1992":0.01,"X2002":0.01}]

To change the format of the JSON file you can choose the argument pretty = TRUE in toJSON, or change an excisting file with minify() or prettify()

In [17]:
# Convert mtcars to a pretty JSON: pretty_json
pretty_json <- toJSON(mtcars, pretty = TRUE)

# Print pretty_json
pretty_json

# Minify pretty_json: mini_json
mini_json <- minify(pretty_json)

# Print mini_json
mini_json

[
  {
    "mpg": 21,
    "cyl": 6,
    "disp": 160,
    "hp": 110,
    "drat": 3.9,
    "wt": 2.62,
    "qsec": 16.46,
    "vs": 0,
    "am": 1,
    "gear": 4,
    "carb": 4,
    "_row": "Mazda RX4"
  },
  {
    "mpg": 21,
    "cyl": 6,
    "disp": 160,
    "hp": 110,
    "drat": 3.9,
    "wt": 2.875,
    "qsec": 17.02,
    "vs": 0,
    "am": 1,
    "gear": 4,
    "carb": 4,
    "_row": "Mazda RX4 Wag"
  },
  {
    "mpg": 22.8,
    "cyl": 4,
    "disp": 108,
    "hp": 93,
    "drat": 3.85,
    "wt": 2.32,
    "qsec": 18.61,
    "vs": 1,
    "am": 1,
    "gear": 4,
    "carb": 1,
    "_row": "Datsun 710"
  },
  {
    "mpg": 21.4,
    "cyl": 6,
    "disp": 258,
    "hp": 110,
    "drat": 3.08,
    "wt": 3.215,
    "qsec": 19.44,
    "vs": 1,
    "am": 0,
    "gear": 3,
    "carb": 1,
    "_row": "Hornet 4 Drive"
  },
  {
    "mpg": 18.7,
    "cyl": 8,
    "disp": 360,
    "hp": 175,
    "drat": 3.15,
    "wt": 3.44,
    "qsec": 17.02,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 2,
    "_row": "Hornet Sportabout"
  },
  {
    "mpg": 18.1,
    "cyl": 6,
    "disp": 225,
    "hp": 105,
    "drat": 2.76,
    "wt": 3.46,
    "qsec": 20.22,
    "vs": 1,
    "am": 0,
    "gear": 3,
    "carb": 1,
    "_row": "Valiant"
  },
  {
    "mpg": 14.3,
    "cyl": 8,
    "disp": 360,
    "hp": 245,
    "drat": 3.21,
    "wt": 3.57,
    "qsec": 15.84,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 4,
    "_row": "Duster 360"
  },
  {
    "mpg": 24.4,
    "cyl": 4,
    "disp": 146.7,
    "hp": 62,
    "drat": 3.69,
    "wt": 3.19,
    "qsec": 20,
    "vs": 1,
    "am": 0,
    "gear": 4,
    "carb": 2,
    "_row": "Merc 240D"
  },
  {
    "mpg": 22.8,
    "cyl": 4,
    "disp": 140.8,
    "hp": 95,
    "drat": 3.92,
    "wt": 3.15,
    "qsec": 22.9,
    "vs": 1,
    "am": 0,
    "gear": 4,
    "carb": 2,
    "_row": "Merc 230"
  },
  {
    "mpg": 19.2,
    "cyl": 6,
    "disp": 167.6,
    "hp": 123,
    "drat": 3.92,
    "wt": 3.44,
    "qsec": 18.3,
    "vs": 1,
    "am": 0,
    "gear": 4,
    "carb": 4,
    "_row": "Merc 280"
  },
  {
    "mpg": 17.8,
    "cyl": 6,
    "disp": 167.6,
    "hp": 123,
    "drat": 3.92,
    "wt": 3.44,
    "qsec": 18.9,
    "vs": 1,
    "am": 0,
    "gear": 4,
    "carb": 4,
    "_row": "Merc 280C"
  },
  {
    "mpg": 16.4,
    "cyl": 8,
    "disp": 275.8,
    "hp": 180,
    "drat": 3.07,
    "wt": 4.07,
    "qsec": 17.4,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 3,
    "_row": "Merc 450SE"
  },
  {
    "mpg": 17.3,
    "cyl": 8,
    "disp": 275.8,
    "hp": 180,
    "drat": 3.07,
    "wt": 3.73,
    "qsec": 17.6,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 3,
    "_row": "Merc 450SL"
  },
  {
    "mpg": 15.2,
    "cyl": 8,
    "disp": 275.8,
    "hp": 180,
    "drat": 3.07,
    "wt": 3.78,
    "qsec": 18,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 3,
    "_row": "Merc 450SLC"
  },
  {
    "mpg": 10.4,
    "cyl": 8,
    "disp": 472,
    "hp": 205,
    "drat": 2.93,
    "wt": 5.25,
    "qsec": 17.98,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 4,
    "_row": "Cadillac Fleetwood"
  },
  {
    "mpg": 10.4,
    "cyl": 8,
    "disp": 460,
    "hp": 215,
    "drat": 3,
    "wt": 5.424,
    "qsec": 17.82,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 4,
    "_row": "Lincoln Continental"
  },
  {
    "mpg": 14.7,
    "cyl": 8,
    "disp": 440,
    "hp": 230,
    "drat": 3.23,
    "wt": 5.345,
    "qsec": 17.42,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 4,
    "_row": "Chrysler Imperial"
  },
  {
    "mpg": 32.4,
    "cyl": 4,
    "disp": 78.7,
    "hp": 66,
    "drat": 4.08,
    "wt": 2.2,
    "qsec": 19.47,
    "vs": 1,
    "am": 1,
    "gear": 4,
    "carb": 1,
    "_row": "Fiat 128"
  },
  {
    "mpg": 30.4,
    "cyl": 4,
    "disp": 75.7,
    "hp": 52,
    "drat": 4.93,
    "wt": 1.615,
    "qsec": 18.52,
    "vs": 1,
    "am": 1,
    "gear": 4,
    "carb": 2,
    "_row": "Honda Civic"
  },
  {
    "mpg": 33.9,
    "cyl": 4,
    "disp": 71.1,
    "hp": 65,
    "drat": 4.22,
    "wt": 1.835,
    "qsec": 19.9,
    "vs": 1,
    "am": 1,
    "gear": 4,
    "carb": 1,
    "_row": "Toyota Corolla"
  },
  {
    "mpg": 21.5,
    "cyl": 4,
    "disp": 120.1,
    "hp": 97,
    "drat": 3.7,
    "wt": 2.465,
    "qsec": 20.01,
    "vs": 1,
    "am": 0,
    "gear": 3,
    "carb": 1,
    "_row": "Toyota Corona"
  },
  {
    "mpg": 15.5,
    "cyl": 8,
    "disp": 318,
    "hp": 150,
    "drat": 2.76,
    "wt": 3.52,
    "qsec": 16.87,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 2,
    "_row": "Dodge Challenger"
  },
  {
    "mpg": 15.2,
    "cyl": 8,
    "disp": 304,
    "hp": 150,
    "drat": 3.15,
    "wt": 3.435,
    "qsec": 17.3,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 2,
    "_row": "AMC Javelin"
  },
  {
    "mpg": 13.3,
    "cyl": 8,
    "disp": 350,
    "hp": 245,
    "drat": 3.73,
    "wt": 3.84,
    "qsec": 15.41,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 4,
    "_row": "Camaro Z28"
  },
  {
    "mpg": 19.2,
    "cyl": 8,
    "disp": 400,
    "hp": 175,
    "drat": 3.08,
    "wt": 3.845,
    "qsec": 17.05,
    "vs": 0,
    "am": 0,
    "gear": 3,
    "carb": 2,
    "_row": "Pontiac Firebird"
  },
  {
    "mpg": 27.3,
    "cyl": 4,
    "disp": 79,
    "hp": 66,
    "drat": 4.08,
    "wt": 1.935,
    "qsec": 18.9,
    "vs": 1,
    "am": 1,
    "gear": 4,
    "carb": 1,
    "_row": "Fiat X1-9"
  },
  {
    "mpg": 26,
    "cyl": 4,
    "disp": 120.3,
    "hp": 91,
    "drat": 4.43,
    "wt": 2.14,
    "qsec": 16.7,
    "vs": 0,
    "am": 1,
    "gear": 5,
    "carb": 2,
    "_row": "Porsche 914-2"
  },
  {
    "mpg": 30.4,
    "cyl": 4,
    "disp": 95.1,
    "hp": 113,
    "drat": 3.77,
    "wt": 1.513,
    "qsec": 16.9,
    "vs": 1,
    "am": 1,
    "gear": 5,
    "carb": 2,
    "_row": "Lotus Europa"
  },
  {
    "mpg": 15.8,
    "cyl": 8,
    "disp": 351,
    "hp": 264,
    "drat": 4.22,
    "wt": 3.17,
    "qsec": 14.5,
    "vs": 0,
    "am": 1,
    "gear": 5,
    "carb": 4,
    "_row": "Ford Pantera L"
  },
  {
    "mpg": 19.7,
    "cyl": 6,
    "disp": 145,
    "hp": 175,
    "drat": 3.62,
    "wt": 2.77,
    "qsec": 15.5,
    "vs": 0,
    "am": 1,
    "gear": 5,
    "carb": 6,
    "_row": "Ferrari Dino"
  },
  {
    "mpg": 15,
    "cyl": 8,
    "disp": 301,
    "hp": 335,
    "drat": 3.54,
    "wt": 3.57,
    "qsec": 14.6,
    "vs": 0,
    "am": 1,
    "gear": 5,
    "carb": 8,
    "_row": "Maserati Bora"
  },
  {
    "mpg": 21.4,
    "cyl": 4,
    "disp": 121,
    "hp": 109,
    "drat": 4.11,
    "wt": 2.78,
    "qsec": 18.6,
    "vs": 1,
    "am": 1,
    "gear": 4,
    "carb": 2,
    "_row": "Volvo 142E"
  }
]

[{"mpg":21,"cyl":6,"disp":160,"hp":110,"drat":3.9,"wt":2.62,"qsec":16.46,"vs":0,"am":1,"gear":4,"carb":4,"_row":"Mazda RX4"},{"mpg":21,"cyl":6,"disp":160,"hp":110,"drat":3.9,"wt":2.875,"qsec":17.02,"vs":0,"am":1,"gear":4,"carb":4,"_row":"Mazda RX4 Wag"},{"mpg":22.8,"cyl":4,"disp":108,"hp":93,"drat":3.85,"wt":2.32,"qsec":18.61,"vs":1,"am":1,"gear":4,"carb":1,"_row":"Datsun 710"},{"mpg":21.4,"cyl":6,"disp":258,"hp":110,"drat":3.08,"wt":3.215,"qsec":19.44,"vs":1,"am":0,"gear":3,"carb":1,"_row":"Hornet 4 Drive"},{"mpg":18.7,"cyl":8,"disp":360,"hp":175,"drat":3.15,"wt":3.44,"qsec":17.02,"vs":0,"am":0,"gear":3,"carb":2,"_row":"Hornet Sportabout"},{"mpg":18.1,"cyl":6,"disp":225,"hp":105,"drat":2.76,"wt":3.46,"qsec":20.22,"vs":1,"am":0,"gear":3,"carb":1,"_row":"Valiant"},{"mpg":14.3,"cyl":8,"disp":360,"hp":245,"drat":3.21,"wt":3.57,"qsec":15.84,"vs":0,"am":0,"gear":3,"carb":4,"_row":"Duster 360"},{"mpg":24.4,"cyl":4,"disp":146.7,"hp":62,"drat":3.69,"wt":3.19,"qsec":20,"vs":1,"am":0,"gear":4,"carb":2,"_row":"Merc 240D"},{"mpg":22.8,"cyl":4,"disp":140.8,"hp":95,"drat":3.92,"wt":3.15,"qsec":22.9,"vs":1,"am":0,"gear":4,"carb":2,"_row":"Merc 230"},{"mpg":19.2,"cyl":6,"disp":167.6,"hp":123,"drat":3.92,"wt":3.44,"qsec":18.3,"vs":1,"am":0,"gear":4,"carb":4,"_row":"Merc 280"},{"mpg":17.8,"cyl":6,"disp":167.6,"hp":123,"drat":3.92,"wt":3.44,"qsec":18.9,"vs":1,"am":0,"gear":4,"carb":4,"_row":"Merc 280C"},{"mpg":16.4,"cyl":8,"disp":275.8,"hp":180,"drat":3.07,"wt":4.07,"qsec":17.4,"vs":0,"am":0,"gear":3,"carb":3,"_row":"Merc 450SE"},{"mpg":17.3,"cyl":8,"disp":275.8,"hp":180,"drat":3.07,"wt":3.73,"qsec":17.6,"vs":0,"am":0,"gear":3,"carb":3,"_row":"Merc 450SL"},{"mpg":15.2,"cyl":8,"disp":275.8,"hp":180,"drat":3.07,"wt":3.78,"qsec":18,"vs":0,"am":0,"gear":3,"carb":3,"_row":"Merc 450SLC"},{"mpg":10.4,"cyl":8,"disp":472,"hp":205,"drat":2.93,"wt":5.25,"qsec":17.98,"vs":0,"am":0,"gear":3,"carb":4,"_row":"Cadillac Fleetwood"},{"mpg":10.4,"cyl":8,"disp":460,"hp":215,"drat":3,"wt":5.424,"qsec":17.82,"vs":0,"am":0,"gear":3,"carb":4,"_row":"Lincoln Continental"},{"mpg":14.7,"cyl":8,"disp":440,"hp":230,"drat":3.23,"wt":5.345,"qsec":17.42,"vs":0,"am":0,"gear":3,"carb":4,"_row":"Chrysler Imperial"},{"mpg":32.4,"cyl":4,"disp":78.7,"hp":66,"drat":4.08,"wt":2.2,"qsec":19.47,"vs":1,"am":1,"gear":4,"carb":1,"_row":"Fiat 128"},{"mpg":30.4,"cyl":4,"disp":75.7,"hp":52,"drat":4.93,"wt":1.615,"qsec":18.52,"vs":1,"am":1,"gear":4,"carb":2,"_row":"Honda Civic"},{"mpg":33.9,"cyl":4,"disp":71.1,"hp":65,"drat":4.22,"wt":1.835,"qsec":19.9,"vs":1,"am":1,"gear":4,"carb":1,"_row":"Toyota Corolla"},{"mpg":21.5,"cyl":4,"disp":120.1,"hp":97,"drat":3.7,"wt":2.465,"qsec":20.01,"vs":1,"am":0,"gear":3,"carb":1,"_row":"Toyota Corona"},{"mpg":15.5,"cyl":8,"disp":318,"hp":150,"drat":2.76,"wt":3.52,"qsec":16.87,"vs":0,"am":0,"gear":3,"carb":2,"_row":"Dodge Challenger"},{"mpg":15.2,"cyl":8,"disp":304,"hp":150,"drat":3.15,"wt":3.435,"qsec":17.3,"vs":0,"am":0,"gear":3,"carb":2,"_row":"AMC Javelin"},{"mpg":13.3,"cyl":8,"disp":350,"hp":245,"drat":3.73,"wt":3.84,"qsec":15.41,"vs":0,"am":0,"gear":3,"carb":4,"_row":"Camaro Z28"},{"mpg":19.2,"cyl":8,"disp":400,"hp":175,"drat":3.08,"wt":3.845,"qsec":17.05,"vs":0,"am":0,"gear":3,"carb":2,"_row":"Pontiac Firebird"},{"mpg":27.3,"cyl":4,"disp":79,"hp":66,"drat":4.08,"wt":1.935,"qsec":18.9,"vs":1,"am":1,"gear":4,"carb":1,"_row":"Fiat X1-9"},{"mpg":26,"cyl":4,"disp":120.3,"hp":91,"drat":4.43,"wt":2.14,"qsec":16.7,"vs":0,"am":1,"gear":5,"carb":2,"_row":"Porsche 914-2"},{"mpg":30.4,"cyl":4,"disp":95.1,"hp":113,"drat":3.77,"wt":1.513,"qsec":16.9,"vs":1,"am":1,"gear":5,"carb":2,"_row":"Lotus Europa"},{"mpg":15.8,"cyl":8,"disp":351,"hp":264,"drat":4.22,"wt":3.17,"qsec":14.5,"vs":0,"am":1,"gear":5,"carb":4,"_row":"Ford Pantera L"},{"mpg":19.7,"cyl":6,"disp":145,"hp":175,"drat":3.62,"wt":2.77,"qsec":15.5,"vs":0,"am":1,"gear":5,"carb":6,"_row":"Ferrari Dino"},{"mpg":15,"cyl":8,"disp":301,"hp":335,"drat":3.54,"wt":3.57,"qsec":14.6,"vs":0,"am":1,"gear":5,"carb":8,"_row":"Maserati Bora"},{"mpg":21.4,"cyl":4,"disp":121,"hp":109,"drat":4.11,"wt":2.78,"qsec":18.6,"vs":1,"am":1,"gear":4,"carb":2,"_row":"Volvo 142E"}]